// Generated by gencpp from file map_manager/StaticObstacleArray.msg
// DO NOT EDIT!


#ifndef MAP_MANAGER_MESSAGE_STATICOBSTACLEARRAY_H
#define MAP_MANAGER_MESSAGE_STATICOBSTACLEARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <map_manager/StaticObstacle.h>

namespace map_manager
{
template <class ContainerAllocator>
struct StaticObstacleArray_
{
  typedef StaticObstacleArray_<ContainerAllocator> Type;

  StaticObstacleArray_()
    : header()
    , obstacles()  {
    }
  StaticObstacleArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::map_manager::StaticObstacle_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::map_manager::StaticObstacle_<ContainerAllocator> >> _obstacles_type;
  _obstacles_type obstacles;





  typedef boost::shared_ptr< ::map_manager::StaticObstacleArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_manager::StaticObstacleArray_<ContainerAllocator> const> ConstPtr;

}; // struct StaticObstacleArray_

typedef ::map_manager::StaticObstacleArray_<std::allocator<void> > StaticObstacleArray;

typedef boost::shared_ptr< ::map_manager::StaticObstacleArray > StaticObstacleArrayPtr;
typedef boost::shared_ptr< ::map_manager::StaticObstacleArray const> StaticObstacleArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_manager::StaticObstacleArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_manager::StaticObstacleArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::map_manager::StaticObstacleArray_<ContainerAllocator1> & lhs, const ::map_manager::StaticObstacleArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.obstacles == rhs.obstacles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::map_manager::StaticObstacleArray_<ContainerAllocator1> & lhs, const ::map_manager::StaticObstacleArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace map_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::map_manager::StaticObstacleArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_manager::StaticObstacleArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_manager::StaticObstacleArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_manager::StaticObstacleArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_manager::StaticObstacleArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_manager::StaticObstacleArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_manager::StaticObstacleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "61c9bb1e78d8bdd31690ec29054c93df";
  }

  static const char* value(const ::map_manager::StaticObstacleArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x61c9bb1e78d8bdd3ULL;
  static const uint64_t static_value2 = 0x1690ec29054c93dfULL;
};

template<class ContainerAllocator>
struct DataType< ::map_manager::StaticObstacleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_manager/StaticObstacleArray";
  }

  static const char* value(const ::map_manager::StaticObstacleArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_manager::StaticObstacleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"StaticObstacle[] obstacles \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: map_manager/StaticObstacle\n"
"std_msgs/Header header\n"
"string name\n"
"uint32 id\n"
"geometry_msgs/Vector3 position\n"
"geometry_msgs/Vector3 size\n"
"float64 yaw\n"
"string semantic_class\n"
"float64 cost_weight\n"
"float64 safety_distance\n"
"std_msgs/ColorRGBA color \n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: std_msgs/ColorRGBA\n"
"float32 r\n"
"float32 g\n"
"float32 b\n"
"float32 a\n"
;
  }

  static const char* value(const ::map_manager::StaticObstacleArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_manager::StaticObstacleArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StaticObstacleArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_manager::StaticObstacleArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_manager::StaticObstacleArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "obstacles: ";
    if (v.obstacles.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::map_manager::StaticObstacle_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.obstacles[i]);
    }
    if (v.obstacles.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_MANAGER_MESSAGE_STATICOBSTACLEARRAY_H
