(cl:defpackage onboard_detector-srv
  (:use )
  (:export
   "GETDYNAMICOBSTACLES"
   "<GETDYNAMICOBSTACLES-REQUEST>"
   "GETDYNAMICOBSTACLES-REQUEST"
   "<GETDYNAMICOBSTACLES-RESPONSE>"
   "GETDYNAMICOBSTACLES-RESPONSE"
   "GETSTATICOBSTACLES"
   "<GETSTATICOBSTACLES-REQUEST>"
   "GETSTATICOBSTACLES-REQUEST"
   "<GETSTATICOBSTACLES-RESPONSE>"
   "GETSTATICOBSTACLES-RESPONSE"
  ))

