// Generated by gencpp from file onboard_detector/GetStaticObstacles.msg
// DO NOT EDIT!


#ifndef ONBOARD_DETECTOR_MESSAGE_GETSTATICOBSTACLES_H
#define ONBOARD_DETECTOR_MESSAGE_GETSTATICOBSTACLES_H

#include <ros/service_traits.h>


#include <onboard_detector/GetStaticObstaclesRequest.h>
#include <onboard_detector/GetStaticObstaclesResponse.h>


namespace onboard_detector
{

struct GetStaticObstacles
{

typedef GetStaticObstaclesRequest Request;
typedef GetStaticObstaclesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetStaticObstacles
} // namespace onboard_detector


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::onboard_detector::GetStaticObstacles > {
  static const char* value()
  {
    return "720433b0b9d7c4c8bbc6acba25184779";
  }

  static const char* value(const ::onboard_detector::GetStaticObstacles&) { return value(); }
};

template<>
struct DataType< ::onboard_detector::GetStaticObstacles > {
  static const char* value()
  {
    return "onboard_detector/GetStaticObstacles";
  }

  static const char* value(const ::onboard_detector::GetStaticObstacles&) { return value(); }
};


// service_traits::MD5Sum< ::onboard_detector::GetStaticObstaclesRequest> should match
// service_traits::MD5Sum< ::onboard_detector::GetStaticObstacles >
template<>
struct MD5Sum< ::onboard_detector::GetStaticObstaclesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::onboard_detector::GetStaticObstacles >::value();
  }
  static const char* value(const ::onboard_detector::GetStaticObstaclesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::onboard_detector::GetStaticObstaclesRequest> should match
// service_traits::DataType< ::onboard_detector::GetStaticObstacles >
template<>
struct DataType< ::onboard_detector::GetStaticObstaclesRequest>
{
  static const char* value()
  {
    return DataType< ::onboard_detector::GetStaticObstacles >::value();
  }
  static const char* value(const ::onboard_detector::GetStaticObstaclesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::onboard_detector::GetStaticObstaclesResponse> should match
// service_traits::MD5Sum< ::onboard_detector::GetStaticObstacles >
template<>
struct MD5Sum< ::onboard_detector::GetStaticObstaclesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::onboard_detector::GetStaticObstacles >::value();
  }
  static const char* value(const ::onboard_detector::GetStaticObstaclesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::onboard_detector::GetStaticObstaclesResponse> should match
// service_traits::DataType< ::onboard_detector::GetStaticObstacles >
template<>
struct DataType< ::onboard_detector::GetStaticObstaclesResponse>
{
  static const char* value()
  {
    return DataType< ::onboard_detector::GetStaticObstacles >::value();
  }
  static const char* value(const ::onboard_detector::GetStaticObstaclesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ONBOARD_DETECTOR_MESSAGE_GETSTATICOBSTACLES_H
